sudo: required
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
deploy:
- provider: pages
  skip_cleanup: true
  repo: wpveda/wpveda.github.io
  github_token: "$GITHUB_TOKEN"
  local_dir: _book
  fqdn: wpveda.com
  target_branch: master
  on:
    branch: master
branches:
  only:
  - master
notifications:
  slack:
    secure: WuuEvACHU25m+GDHhehZTPv5NZHzB+aUNgjteICtsX3+iaC21ykF/9wsd8trCN2/8TjlQksyEEtllA+EmFWGyzCZjle9Lg38ilxYoHufCIFDV0AIJHWNONCywe7/F6RLy7OPmuKHYEbP70p/BuRrchfaS8e/GdjueIjlcDlGpiA=
