sudo: required

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules # NPM packages

install:
  - npm install -g gitbook-cli

script:
  - gitbook install
  - gitbook build
#  - rm -v _book/.travis.yml

deploy:
    #Push the generated gitbook html to the gh-pages branch
  - provider: pages
    skip_cleanup: true
    repo: wpveda/wpveda.github.io
    github_token: $GITHUB_TOKEN
    local_dir: _book
    target_branch: gh_pages
    on:
      branch: master
    #Upload the pdf of the docs as a release tagged with the build number

branches:
  only:
    - master

# notifications:
  # email: false
